### ISSUE TITLE
MineColonies Recipe does not work

### ISSUE THREAD

**Issue by Fastdragon1107** [P3rf3ctXZer0/Minecraft-Evolved-Series#10]
When I try to create any thing from the minecolonies mod I get an error and the recipe won't work

**Comment by P3rf3ctXZer0** [comment]
I need to know which recipe latest.log and screenshot if possible to know what is going on.

**Comment by P3rf3ctXZer0** [comment]
https://ldtteam.github.io/MinecoloniesWiki/
